package com.mybatis.mapper;

import com.mybatis.model.FilterTable;

public interface FilterTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int insert(FilterTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated
     */
    int insertSelective(FilterTable record);
}