package com.mybatis.model;

public class FilterTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.vri
     *
     * @mbggenerated
     */
    private Double vri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.vri
     *
     * @return the value of filter.vri
     *
     * @mbggenerated
     */
    public Double getVri() {
        return vri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.vri
     *
     * @param vri the value for filter.vri
     *
     * @mbggenerated
     */
    public void setVri(Double vri) {
        this.vri = vri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.code
     *
     * @return the value of filter.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.code
     *
     * @param code the value for filter.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.name
     *
     * @return the value of filter.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.name
     *
     * @param name the value for filter.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}